[replica]
nreplicas = 
nprocs_per_replica = 

kTstart = 
kTend = 

nsteps = 

RXtrial_frequency = 
sample_frequency = 
print_frequency = 
reload = false

[solver]
type = 
path= 
base_input_dir = 
perturb = 
run_scheme = 

[observer]
type = 'default'

