supercell = [2,2,2]

[base_structure]
species = ['Ba']
fix = false

[[defect_structure]]
site_center_species = ['Zr']
[[defect_structure.groups]]
name = 'Zr'
num = 6
[[defect_structure.groups]]
name = 'Y'
num = 2

[[defect_structure]]
site_center_species = ['O']
[[defect_structure.groups]]
name = 'O'
num = 23
[[defect_structure.groups]]
name = 'VO'
species = []
num = 1


# atom groups residing on site centers are determined from input
# structure by default, although they can be controlled as follows

#[[defect_structure.groups]]
#name = 'Mg'
#species = ['Mg']
#coords = [[[0,0,0]]]
#num = 64

#[[defect_structure.groups]]
#name = 'Al'
#species = ['Al']
#coords = [[[0,0,0]]]
#num = 128
