supercell = [2,2,2]

[base_structure]
species = []
fix = false

[[defect_structure]]
site_center_species = ['Cu', 'Zn']


# atom groups residing on site centers are determined from input
# structure by default, although they can be controlled as follows

#[[defect_structure.groups]]
#name = 'Mg'
#species = ['Mg']
#coords = [[[0,0,0]]]
#num = 64

#[[defect_structure.groups]]
#name = 'Al'
#species = ['Al']
#coords = [[[0,0,0]]]
#num = 128
