name: test for building doc

on: [push]

jobs:
  check-build-doc:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Prepare LaTeX env
      run: |
        sudo apt update
        sudo apt install \
          texlive-latex-recommended texlive-latex-extra texlive-xetex \
          texlive-lang-japanese texlive-fonts-recommended texlive-fonts-extra latexmk
        kanji-config-updmap-sys ipaex

    - name: Install python packages
      run: |
        python -m pip install --upgrade pip
        pip install sphinx sphinx_rtd_theme

    - name: Build
      run: |
        cd ${GITHUB_WORKSPACE}/docs
        sh make.sh
